chatterbot/ext/django_chatterbot/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import ChatterBotView


urlpatterns = [
    url(
        r'^$',
        ChatterBotView.as_view(),
        name='chatterbot',
    ),
]

rbcFintech/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from chatterbot.ext.django_chatterbot import urls as chatterbot_urls
from rbcFintech.views import ChatterBotAppView

urlpatterns = [
	url(r'^$', ChatterBotAppView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^api/chatterbot/', include(chatterbot_urls, namespace='chatterbot')),
]

chatterbot/ext/django_chatterbot/models.py
from django.db import models


class Statement(models.Model):
    """A short (<255) chat message, tweet, forum post, etc"""

    text = models.CharField(
        unique=True,
        blank=False,
        null=False,
        max_length=255
    )

    def __str__(self):
        if len(self.text.strip()) > 60:
            return '{}...'.format(self.text[:57])
        elif len(self.text.strip()) > 0:
            return self.text
        return '<empty>'


class Response(models.Model):
    """Connection between a response and the statement that triggered it

    Comparble to a ManyToMany "through" table, but without the M2M indexing/relations.

    Only the text and number of times it has occurred are currently stored.
    Might be useful to store additional features like language, location(s)/region(s),
    first created datetime(s), username, user full name, user gender, etc.
    A the very least occurrences should be an FK to a meta-data table with this info.
    """

    statement = models.ForeignKey(
        'Statement',
        related_name='in_response_to'
    )

    response = models.ForeignKey(
        'Statement',
        related_name='+'
    )

    unique_together = (('statement', 'response'),)

    occurrence = models.PositiveIntegerField(default=0)

    def __str__(self):
        s = self.statement.text if len(self.statement.text) <= 20 else self.statement.text[:17] + '...'
        s += ' => '
        s += self.response.text if len(self.response.text) <= 40 else self.response.text[:37] + '...'
        return s

chatterbot/ext/django_chatterbot/views.py
from django.views.generic import View
from django.http import JsonResponse
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
import json


class ChatterBotViewMixin(object):

    chatterbot = ChatBot(**settings.CHATTERBOT)
    
    from chatterbot.trainers import ChatterBotCorpusTrainer

    chatterbot.set_trainer(ChatterBotCorpusTrainer)

    chatterbot.train(
        "chatterbot.corpus.english",
        "chatterbot.corpus.english.greetings",
        "chatterbot.corpus.english.conversations"
    )


class ChatterBotView(ChatterBotViewMixin, View):

    def _serialize_recent_statements(self):
        if self.chatterbot.recent_statements.empty():
            return []

        recent_statements = []

        for statement, response in self.chatterbot.recent_statements:
            recent_statements.append([statement.serialize(), response.serialize()])

        return recent_statements

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            data = json.loads(request.body)
            input_statement = data.get('text')
        else:
            input_statement = request.POST.get('text')

        response_data, confidence = self.chatterbot.get_response(input_statement, get_confidence=True)
        response_data['confidence'] = confidence
        return JsonResponse(response_data, status=200)

    def get(self, request, *args, **kwargs):
        data = {
            'detail': 'You should make a POST request to this endpoint.',
            'name': self.chatterbot.name,
            'recent_statements': self._serialize_recent_statements()
        }

        # Return a method not allowed response
        return JsonResponse(data, status=405)

    def patch(self, request, *args, **kwargs):
        data = {
            'detail': 'You should make a POST request to this endpoint.'
        }

        # Return a method not allowed response
        return JsonResponse(data, status=405)

    def delete(self, request, *args, **kwargs):
        data = {
            'detail': 'You should make a POST request to this endpoint.'
        }

        # Return a method not allowed response
        return JsonResponse(data, status=405)


rbcFintech/views.py
from django.views.generic.base import TemplateView


class ChatterBotAppView(TemplateView):
	template_name = "app.html"

rbcFintech/templates/app.html
{% load staticfiles %}
<!doctype html>
<html>

<head>
    <title>Ask Winston</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/star.css' %}">

    <!-- Alternate the background color of the output rows -->
    <style>
        .list-group-item:nth-child(even) {
            background-color: #eee;
        }
        
        .js-chat-log {
            min-height: 400px;
            max-height: 400px;
            overflow-y: auto;
            overflow-x: hidden;
        }
        
        body {}
    </style>
</head>

<body>
    <div class="container">
        <div class="page-header text-center">
            <h1>Winston</h1>

            <div class="view">
                <div class="plane main">
                    <div class="circle"></div>
                    <div class="circle"></div>
                    <div class="circle"></div>
                    <div class="circle"></div>
                    <div class="circle"></div>
                    <div class="circle"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
                <div class="list-group js-chat-log scrollbar-dynamic">
                </div>

                <div class="input-group input-group-lg">
                    <input type="text" class="form-control js-text" placeholder="Type something to begin..." />
                    <span class="input-group-btn">
              {% csrf_token %}
              <button class="btn btn-primary js-say"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
          </span>
                </div>

            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/js.cookie.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'js/jq-init.js' %}"></script>
    <script>
        $(document).ready(function () {
            var chatterbotUrl = '{% url "chatterbot:chatterbot" %}';
            var csrftoken = Cookies.get('csrftoken');


            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            var $chatlog = $('.js-chat-log');
            var $input = $('.js-text');

            var $sayButton = $('.js-say');



            function createRow(text, cardClass, confidence) {
                function rowGenerator(content) {
                    var confidencePercent = Math.round(confidence / 1 * 100);
                    var progressbarDiv = '<div class="progress">' +
                        '<div class="progress-bar" role="progressbar"' +
                        'aria-valuenow="' + confidencePercent + '" aria-valuemin="0"' +
                        'aria-valuemax="100"' +
                        'style="width: ' + confidencePercent + '%">' +
                        confidencePercent + '% Confidence</div></div>';


                    var div = '<div class="panel panel-' + cardClass + '"><div class="panel-body">' +
                        content + '</div>';
                    if (confidence !== null)
                        div += '<div class="panel-footer">' + progressbarDiv + '</div></div>';
                    else
                        div += '</div>';
                    return div;
                }


                var $row = $(rowGenerator(text));
                $row.appendTo($chatlog);
            }

            function submitInput() {
                var inputData = {
                    'text': $input.val()
                }

                // Display the user's input on the web page
                createRow(inputData.text, 'primary', null);
                var $submit = $.ajax({
                    type: 'POST'
                    , url: chatterbotUrl
                    , data: JSON.stringify(inputData)
                    , contentType: 'application/json'
                });

                $submit.done(function (statement) {
                    createRow(statement.text, 'default', statement.confidence);

                    // Clear the input field
                    $input.val('');
                    $chatlog.scrollTop($chatlog[0].scrollHeight);
                });

                $submit.fail(function () {
                    // TODO: Handle errors
                });
            }

            $sayButton.click(function () {
                submitInput();
            });

            $input.keydown(function (event) {
                // Submit the input when the enter button is pressed
                if (event.keyCode == 13) {
                    submitInput();
                }
            });
        });
    </script>
</body>

</html>